name: Terraform workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          TF_VAR_RENDER_OWNER_ID: ${{ secrets.RENDER_OWNER_ID }}
          TF_VAR_GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          TF_VAR_GHCR_PAT: ${{ secrets.GHCR_PAT }}
          TF_VAR_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          TF_VAR_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Wait for Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          approvers: ${{ secrets.GHCR_USERNAME }}
          minimum-approvals: 1
          secret: ${{ secrets.GITHUB_TOKEN }} # - Behind the scenes temporary token generated

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          TF_VAR_RENDER_OWNER_ID: ${{ secrets.RENDER_OWNER_ID }}
          TF_VAR_GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          TF_VAR_GHCR_PAT: ${{ secrets.GHCR_PAT }}
          TF_VAR_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          TF_VAR_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          TF_VAR_SECRET_KEY: ${{ secrets.SECRET_KEY }}